### ISSUE TITLE
Can you upgrade to support Layui 2.x?

### ISSUE THREAD

**Issue by ScottHuangZL** [BrotherMa/layuiCMS#3]
Can you upgrade to support Layui 2.x?

**Comment by wujunze** [comment]
@ScottHuangZL   现在是Layui几?

**Comment by ScottHuangZL** [comment]
You can ignore this request.  I am no plan to use layuiCMS anymore.

**Comment by wujunze** [comment]
@ScottHuangZL  为什么不使用layuiCMS了?   你使用了什么后台UI框架?

**Comment by ScottHuangZL** [comment]
@wujunze I use Yii/Yii2.    And plan add VueJs.  Play with ReactJs recently.

**Comment by wujunze** [comment]
@ScottHuangZL  哦哦  React.js还不错  我们前端在用
